version: "3.6"
services:
  jenkins:
    image: prime-local.artifactory-espoo1.int.net.nokia.com/ndcsci/jenkins02:v2.387
    restart: always
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
    environment:
      JAVA_OPTS: "-Xmx4096m -Djava.awt.headless=true"
